### ISSUE TITLE
import pyglet, i already import in conda, where else?

### ISSUE THREAD

**Issue by GabrielMendesdc** [TheWebCrafters/PyCraft#20]
Traceback (most recent call last):
  File "C:\Users\pdv\PyCraft\__main__.py", line 1, in <module>
    import pyglet
ModuleNotFoundError: No module named 'pyglet'

I already install pyglet in my conda env. what else i do to play the game?

 - OS:  windows 10
 - Browser chrome
 - Version v94

**Comment by GabrielMendesdc** [comment]
ok dude, sorry if i disturb you

**Comment by e-coders** [comment]
...

**Comment by Genius398** [comment]
> ok dude, sorry if i disturb you

No problem I mentioned that guy

**Comment by Genius398** [comment]
> Hi @TheWebCrafters/everyone , sorry but I won't be available for some time as I am currently working on some of my own projects. Also I don't really do Python, so please don't ping me for a bit.
> 
> Regards,
> @Adatta1276 

Sorry 😞

**Comment by Adatta1276** [comment]
> ok dude, sorry if i disturb you

No problem, but I kind of am busy...

**Comment by Adatta1276** [comment]
> > Hi @TheWebCrafters/everyone , sorry but I won't be available for some time as I am currently working on some of my own projects. Also I don't really do Python, so please don't ping me for a bit.
> > Regards,
> > @Adatta1276
> 
> Sorry 😞

No worries

**Comment by somePythonProgrammer** [comment]
@GabrielMendesdc Please note that this application has not been tested in anaconda. 
You can run it in python. Do `python -m pip install pyglet==3.3.0`, or else it gives an error.
The application will not run on pyglet versions other than v3 in future versions.

**Comment by somePythonProgrammer** [comment]
Also, the conda-forge version for pyglet is pretty old, I'm not sure if the game will run. So the best option is to use python instead of anaconda.
